---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Check existence of a previously generated wireguard host configuration
- name: Check existence of a previously generated wireguard configuration
  stat:
    path: "{{ playbook_dir }}/../configuration/{{ host_id }}_wg.conf"
  register: host_wg_conf_file

# Check existence of a previously generated wireguard local configuration for the host
- name: Check existence of a previously generated wireguard local configuration for the host
  stat:
    path: "{{ playbook_dir }}/../configuration/{{ host_id }}_wg_local.conf"
  register: local_wg_conf_file


# Generate wireguard host private key
#
- name: Generate wireguard host private key
  shell: "wg genkey"
  register: generated_host_private_key
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Generate wireguard host public key
#
- name: Generate wireguard host public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_host_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_host_public_key
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Generate wireguard local private key
#
- name: Generate wireguard local private key
  shell: "wg genkey"
  register: generated_local_private_key
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Generate wireguard local public key
#
- name: Generate wireguard local public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_local_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_local_public_key
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Generate wireguard preshared key
#
- name: Generate wireguard preshared key
  command: "wg genpsk"
  register: generated_preshared_key
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Create host wireguard configuration file
#
- name: Create host wireguard configuration file
  template:
    mode: 644
    owner: root
    group: root
    dest: "{{ playbook_dir }}/../configuration/{{ host_id }}_wg.conf"
    src: ryo-host.conf.j2
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Create local wireguard configuration file
#
- name: Create local wireguard configuration file
  template:
    mode: 640
    owner: root
    group: root
    dest: "{{ playbook_dir }}/../configuration/{{ host_id }}_wg_local.conf"
    src: ryo-local.conf.j2
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Copy local wireguard configuration file to /etc/wireguard
#
- name: Copy local wireguard configuration file to wireguard config
  template:
    mode: 640
    owner: root
    group: root
    dest: "/etc/wireguard/{{ host_id }}.conf"
    src: ryo-local.conf.j2
  when: (not host_wg_conf_file.stat.exists) or (not local_wg_conf_file.stat.exists)


# Enable wireguard interface {{ host_id }} as service
#
- name: Enable wireguard interface {{ host_id }} as service
  service:
    name: "wg-quick@{{ host_id }}"
    enabled: yes
    state: restarted
