---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Generate wireguard host private key
#
- name: Generate wireguard host private key
  shell: "wg genkey"
  register: generated_host_private_key


# Generate wireguard host public key
#
- name: Generate wireguard host public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_host_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_host_public_key


# Generate wireguard local private key
#
- name: Generate wireguard local private key
  shell: "wg genkey"
  register: generated_local_private_key


# Generate wireguard local public key
#
- name: Generate wireguard local public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_local_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_local_public_key


# Generate wireguard preshared key
#
- name: Generate wireguard preshared key
  command: "wg genpsk"
  register: generated_preshared_key


# Create host wireguard configuration file
#
- name: Create host wireguard configuration file
  template:
    mode: 644
    owner: root
    group: root
    dest: "{{ playbook_dir }}/../configuration/{{ host_id }}.conf"
    src: ryo-host.conf.j2


# Create local wireguard configuration file
#
- name: Create local wireguard configuration file
  template:
    mode: 640
    owner: root
    group: root
    dest: "/etc/wireguard/{{ host_id }}.conf"
    src: ryo-local.conf.j2


# Enable wireguard interface {{ host_id }} as service
#
- name: Enable wireguard interface {{ host_id }} as service
  service:
    name: "wg-quick@{{ host_id }}"
    enabled: yes
    state: restarted
