---
- name: Provision <PROJECT COMPONENT NAME> container image
  hosts: packer

  vars_files:
    - "{{ playbook_dir }}/../../configuration/configuration.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    # FURTHER ROLES DEPEND ON THE PROJECT
    - role: install-TEMPLATE
    - role: set-up-TEMPLATE
