---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Add entry for host consul server in consul retry_join_wan on control-node
#
- name: Add entry for host consul server in consul retry_join_wan
  lineinfile:
    dest: /etc/consul.d/consul.hcl
    line: '"{{ lxd_host_network_part }}.1",'
    insertafter: '^retry_join_wan'
    state: present
  register: local_consul_changes_made


# Restart consul service on control-node
#
- name: Restart consul service
  service:
    name: consul
    state: restarted
  when: local_consul_changes_made is changed
  