---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

#-----------------------------------------------------------------------------------------------------------------------------------
# Change the SSH port, disable SSH password authentication, disallow root login and allow only the non-root user to log in via SSH
#-----------------------------------------------------------------------------------------------------------------------------------

# Change the SSH port
#
- name: Change the SSH port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#Port'
    line: "Port {{ host_new_ssh_port }}"


# Disable SSH password authentication
#
- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(# *)?PasswordAuthentication'
    line: 'PasswordAuthentication no'


# Disallow root login
#
- name: Disallow root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(# *)?PermitRootLogin'
    line: 'PermitRootLogin no'


# Allow only the non-root user to log in via SSH
#
- name: Allow only the non-root user to log in via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ host_non_root_user }}"


# Set ChallengeResponseAuthentication in SSH config file (no 2FA)
#
- name: Set ChallengeResponseAuthentication in SSH config file (no 2FA)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(# *)?ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
