---
- name: Copy wireguard configuration file
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /etc/wireguard/wg0.conf
    src: "{{ playbook_dir }}/../configuration/{{ host_hostname }}.conf"
    force: yes
  register: changes_made


- name: Enable wg0 as service
  service:
    name: wg-quick@wg0
    enabled: yes
    state: restarted
