---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Copy wireguard configuration file
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /etc/wireguard/wg0.conf
    src: "{{ playbook_dir }}/../configuration/{{ host_id }}_wg.conf"
    force: yes
  register: host_wg_config_changes_made


- name: Enable wg0 as service
  service:
    name: wg-quick@wg0
    enabled: yes
    state: restarted
  when: host_wg_config_changes_made is changed
  