---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

## Generic directory for LXD container persistent storage
## ------------------------------------------------------

## Create directories on host to be mounted in containers

- name: Create a directory for container mounts
  file:
    path: /var/containers
    state: directory
    mode: '0755'

