---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install ndppd
  apt:
    name: ndppd
    update_cache: yes
    state: present
  when: host_public_ipv6
