---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Copy ndppd configuration
  template:
    mode: 0660
    owner: root
    group: root
    dest: /etc/ndppd.conf
    src: ndppd.conf.j2
    force: yes
  register: changes_made
  when: host_public_ipv6
