---
## Generic directory for LXD container persistent storage
## ------------------------------------------------------

## Create directories on host to be mounted in containers

- name: Create a directory for container mounts
  file:
    path: /var/containers
    state: directory
    mode: '0755'


## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

## Create directory for project containers

- name: Create a directory for container mounts for this project
  file:
    path: /var/containers/ryo-grav-cms
    state: directory
    mode: '0755'

### Certbot directory

- name: Create a directory to mount in certbot containers
  file:
    path: /var/containers/ryo-grav-cms/certbot
    state: directory
    mode: '0755'


### TLS certificates directory

- name: Create a directory to mount in containers needing TLS certificates
  file:
    path: /var/containers/ryo-grav-cms/tls
    state: directory
    mode: '0755'


### HAProxy directory

- name: Create a directory to mount in HAProxy containers needing TLS certificates
  file:
    path: /var/containers/ryo-grav-cms/tls/haproxy
    state: directory
    mode: '0755'


### Website directories

- name: Create a directory for website content
  file:
    path: /var/containers/ryo-grav-cms/website
    state: directory
    mode: '0755'

- name: Create a directory for grav content
  file:
    path: /var/containers/ryo-grav-cms/website/grav
    state: directory
    mode: '0755'
