---
# Not needed for all rollyourown.xyz projects
# Set up virtual network interface veth0 if the value of the variable host_veth0_enable in host_configuration.yml is true,
# otherwise skip
#
- name: Copy veth0 netdev configuration file from template
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/systemd/network/00-veth0.netdev
    src: 00-veth0.netdev.j2
    force: yes
    backup: yes
  register: changes_made
  when: host_veth0_enable

- name: Copy veth0 netplan configuration file from template
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/netplan/10-veth0.yaml
    src: 10-veth0.yaml.j2
    force: yes
    backup: yes
  register: changes_made
  when: host_veth0_enable
