---

## Add the control node CA cert as trusted

- name: Ensure certs directory exists
  file:
    path: /usr/local/share/ca-certificates
    state: directory

- name: Install CA certificate to certs directory
  copy:
    mode: 0664
    owner: root
    group: root
    dest: "/usr/local/share/ca-certificates/control-node-ca.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"

- name: Update certificate index
  shell:
    cmd: /usr/sbin/update-ca-certificates


## Add remotes configuration file on control node

## Ensure the local non-root user lxd configuration directory is present

- name: Ensure the local non-root user lxd configuration directory is present
  file:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/"
    state: directory

- name: Add remotes configuration on control node
  template:
    mode: 0664
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/config.yml"
    src: config.yml.j2


## Add control node client certificate and key

- name: Copy control node client certificate
  copy:
    mode: 0664
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/client.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.crt"

- name: Copy control node client private key
  copy:
    mode: 0600
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/client.key"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.key"


## Add project host server certificate

- name: Ensure servercerts directory exists
  file:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/servercerts"
    state: directory

- name: Copy project host server certificate
  copy:
    mode: 0664
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/servercerts/{{ project_id }}.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.crt"


## Add control node server certificate and key

- name: Copy control node server certificate
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.crt"

- name: Copy control node server private key
  copy:
    mode: 0600
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.key"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.key"


## Enable PKI mode: copy CA certificate to client and server configuration

- name: Copy CA certificate to control node server configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.ca"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"

- name: Copy CA certificate to control node client configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/client.ca"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"


## Add the project host as LXD trusted TLS client for the control node

- name: Add project host as LXD trusted TLS client for the control node
  shell:
    cmd: 'lxc config trust add {{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.crt'
  become: yes
  become_user: "{{ local_non_root_user }}"
