---

## Add remotes configuration file on control node

## Ensure the local non-root user snap lxd common configuration directory is present

- name: Ensure the local non-root user snap lxd common configuration directory is present
  file:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "/home/{{ local_non_root_user }}/snap/lxd/common/config/"
    state: directory

- name: Add remotes configuration in control node remotes config file
  blockinfile:
    path: "/home/{{ local_non_root_user }}/snap/lxd/common/config/config.yml"
    insertafter: "^remotes:"
    block: |2
        {{ host_id }}:
          addr: https://{{ wireguard_address_network_part }}.2:8443
          auth_type: tls
          project: default
          protocol: lxd
          public: false
    marker: "  # {mark} ANSIBLE MANAGED BLOCK for {{ host_id }}"


## Add project host server certificate

- name: Ensure servercerts directory exists
  file:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "/home/{{ local_non_root_user }}/snap/lxd/common/config/servercerts"
    state: directory

- name: Copy project host server certificate
  copy:
    mode: 0664
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "/home/{{ local_non_root_user }}/snap/lxd/common/config/servercerts/{{ host_id }}.crt"
    src: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-server.crt"
