---
- name: Remove host as LXD remote on local machine if already present
  shell:
    cmd: 'lxc remote remove {{ host_hostname }}'
  become: yes
  become_user: "{{ local_non_root_user }}"
  ignore_errors: yes


- name: Clear any previous LXD certificates on local machine
  file:
    path: "/home/{{ local_non_root_user }}/.config/lxc/servercerts/{{ host_hostname }}.pem"
    state: absent
  with_items:
    - "/home/{{ local_non_root_user }}/.config/lxc/servercerts/{{ host_hostname }}.pem"
    - /var/snap/lxd/common/lxd/server.crt
    - /var/snap/lxd/common/lxd/server.key


- name: Add host as LXD remote on local machine
  shell:
    cmd: 'lxc remote add {{ host_hostname }} {{ wireguard_address_network_part }}.2 --accept-certificate=true --auth-type="tls" --password="{{ lxd_core_trust_password }}" --public=false'
  become: yes
  become_user: "{{ local_non_root_user }}"
