---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


## Ensure the host non-root user snap lxd common configuration directory is present
- name: Ensure the host non-root user snap lxd common configuration directory is present
  file:
    owner: "{{ host_non_root_user }}"
    group: "{{ host_non_root_user }}"
    path: "/home/{{ host_non_root_user }}/snap/lxd/common/config/"
    state: directory


## Add ubuntu-minimal remote configuration to control node LXD remotes config file
- name: Add ubuntu-minimal remote configuration to control node LXD remotes config file
  blockinfile:
    path: "/home/{{ host_non_root_user }}/snap/lxd/common/config/config.yml"
    insertafter: "^remotes:"
    block: |2
        ubuntu-minimal:
          addr: https://cloud-images.ubuntu.com/minimal/releases
          protocol: simplestreams
          public: true
    marker: "  # {mark} ANSIBLE MANAGED BLOCK for ubuntu-minimal"
