---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Update package cache and ensure all packages are updated
  apt:
    upgrade: 'yes'
    update_cache: yes
  register: changes_made

- name: Autoremove unused packages
  apt:
    autoremove: yes
  register: changes_made

- name: Reboot the machine
  reboot:
  when: changes_made is changed
