---
# Install chrony and enable as service
#
- name: Install chrony
  apt:
    name: chrony
    update_cache: yes
    state: present
  register: changes_made

- name: Ensure chrony service is enabled and started
  service:
    name: chrony
    enabled: yes
    state: started
  register: changes_made


# Install nano - optional, e.g. for inspection of host config files
#
- name: Install nano
  apt:
    name: nano
    update_cache: yes
    state: present
  register: changes_made


# Install glances - optional, e.g. for inspecting server resource usage
#
- name: Install glances
  apt:
    name: glances
    update_cache: yes
    state: present
  register: changes_made
