---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

# Install chrony and enable as service
#
- name: Install chrony
  apt:
    name: chrony
    update_cache: yes
    state: present
  register: changes_made

- name: Ensure chrony service is enabled and started
  service:
    name: chrony
    enabled: yes
    state: started
  register: changes_made


# Install nano - optional, e.g. for inspection of host config files
#
- name: Install nano
  apt:
    name: nano
    update_cache: yes
    state: present
  register: changes_made


# Install unzip
#
- name: Install unzip
  apt:
    name: unzip
    update_cache: yes
    state: present
  register: changes_made


# Install rsync
#
- name: Install rsync
  apt:
    name: rsync
    update_cache: yes
    state: present
