---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Set hostname
  hostname:
    name: "{{ host_id }}"
    use: systemd
  register: changes_made
  