---
- name: Restore persistent storage from a backup for {{ id }} containers on {{ host_id }}
  hosts: host_wireguard_ip
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Project configuration
    - "{{ playbook_dir }}/../../{{ id }}/configuration/configuration_{{ host_id }}.yml"

  vars:
    ansible_port: "{{ host_new_ssh_port }}"
    ansible_user: "{{ host_non_root_user }}"
    ansible_ssh_pass: "{{ host_non_root_user_password }}"
    ansible_ssh_private_key_file: "{{ local_non_root_user_ssh_private_key_file_path }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: yes
    ansible_become_method: sudo
    transfer_method: scp  
  
  tasks:

    - name: Remove persistent storage for {{ id }} containers on {{ host_id }}
      file:
        path: "/var/containers/{{ id }}"
        state: absent

    - name: Unarchive persistent storage backup for {{ id }} containers to {{ host_id }}
      unarchive:
        src: "{{ playbook_dir }}/backups/backup-{{ host_id }}-{{ id }}-{{ backup_stamp }}.tar.gz"
        dest: "/var/containers"
        extra_opts:
        - --same-owner
        - -p
