# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

## WARNING: After adding configuration, never push this file, with secrets, 
# to a repository or publish in any other way!


#----------------------------
# REQUIRED Host Configuration
#----------------------------

# Basic host configuration
#-------------------------

# Add the IPv4 address of your host server here.
# This is the IPv4 address that your control node will use to reach your host server.
# !! Make sure that this IP address is also configured in the inventory file.
#
# NOTE:
#   - If you are using a VPS or server from a hosting provider, this will be
#     **the same** as the host_pubic_ip parameter below
#   - If you are running your own host server in your home or office network, this
#     will be a private IP address from your home or office network
host_control_ip: <IP ADDRESS>

# Add the public IPv4 address of your host server here.
# This is the IPv4 address from which your host server is reachable via public internet.
#
# NOTE:
#   - If you are using a VPS or server from a hosting provider, this will be
#     **the same** as the host_control_ip parameter above
#   - If you are running your own host server in your home or office network, this
#     will be **different** to the host_control_ip parameter above
host_public_ip: <IP ADDRESS>

# Change to true if you host server has been assigned a public IPv6 prefix
host_public_ipv6: false
# If your host server has been assigned a public IPv6 prefix, then add the following parameters,
# otherwise, leave undefined.
# Add the public IPv6 prefix for your host server here (usually a /56 or /64 prefix).
# This is the IPv6 prefix provided to you by your hosting provider.
# REMOVE any trailing colons (e.g. "::") and DO NOT add the prefix length (e.g. "/56" or "/64").
host_public_ipv6_prefix: <IPV6 PREFIX>
# Add the public IPv6 address of your host server here.
# This is the IPv6 address from which your host server is reachable via public internet.
host_public_ipv6_address: <IPV6 ADDRESS>

# Set the default SSH port, as provided by your server hosting provider
host_initial_ssh_port: 22

# Set the default root username here (probably 'root'), as provided by 
# your server hosting provider
host_root_user: root

# Set the default root password here, as provided by your server 
# hosting provider
host_root_password: <INITIAL PASSWORD>

# Define a non-root username
host_non_root_user: <USER_NAME>

# SECRET: Set a strong user password here. 
host_non_root_user_password: <PASSWORD>


#----------------------------------------------------------------------------
# DEFAULT Configuration - leave as default unless you know what you are doing
#----------------------------------------------------------------------------

# Host SSH configuration
#-----------------------

# Leave as default or change according to preference
host_new_ssh_port: 2222


# Host wireguard configuration
#-----------------------------

# Leave as default or change according to preference
host_wireguard_port: 52222

# Leave the following settings as default if this is the first host managed
# by the control node. Change if other hosts are already configured on the control node.
# Make sure that these settings DO NOT overlap with any other host - e.g. if
# other hosts managed by the control node use "10.0.1" / "fd10:10:0:1" and
# "10.0.2" / "fd10:10:0:2", then set these to "10.0.3" / "fd10:10:0:3"
# MAKE SURE that the network part for [host_wireguard_ip] and [host_wireguard_ip6]
# are also changed in the host inventory file
# !! Make sure that the network prefix for [host_wireguard_ip] and [host_wireguard_ip6]
# !! in the inventory file are consistent with these parameters
wireguard_address_network_part: "10.0.1"
wireguard_address_network_ipv6_prefix: "fd10:10:0:1"


# Host LXD configuration
#-----------------------------

# Leave the following settings as default if this is the first host managed
# by the control node. Change if other hosts are already configured on the control node.
# Make sure that these settings DO NOT overlap with any other host LXD networks.
# For example, if other hosts managed by the control node use "10.10.1" / "1" 
# and "10.10.2" / "2", then set these to "10.10.3" / "3".
lxd_host_network_part: "10.10.1"
lxd_host_network_ipv6_subnet: "1"

# The following setting should not need to be changed.
lxd_host_private_ipv6_prefix: "fd10:10:10:1"

# Change according to the available storage on the host. 
# Set to leave at least 5GB for the operating system.
lxd_storage_pool_size: 40GB

