---
- name: Set up LXD on the host
  hosts: host_wireguard_ip
  
  vars_files:
    - "{{ playbook_dir }}/../../../../ryo-control-node/configuration/configuration.yml"
    - "{{ playbook_dir }}/../../../configuration/configuration.yml"
  
  vars:
    ansible_port: "{{ host_new_ssh_port }}"
    ansible_user: "{{ host_non_root_user }}"
    ansible_ssh_pass: "{{ host_non_root_user_password }}"
    ansible_ssh_private_key_file: "{{ local_non_root_user_ssh_private_key_file_path }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: yes
    ansible_become_method: sudo
    transfer_method: scp  
  
  roles:
    - role: lxd-setup
    - role: lxd-tune-host
    - role: lxd-container-directories-generic
    - role: reboot-host


- name: If needed, initialise LXD on local machine
  hosts: local

  vars_files:
    - "{{ playbook_dir }}/../../../../ryo-control-node/configuration/configuration.yml"

  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"
  
  roles:
    - role: lxd-initialise-local


- name: Initialise LXD on host
  hosts: host_wireguard_ip
  
  vars_files:
    - "{{ playbook_dir }}/../../../../ryo-control-node/configuration/configuration.yml"
    - "{{ playbook_dir }}/../../../configuration/configuration.yml"
  
  vars:
    ansible_port: "{{ host_new_ssh_port }}"
    ansible_user: "{{ host_non_root_user }}"
    ansible_ssh_pass: "{{ host_non_root_user_password }}"
    ansible_ssh_private_key_file: "{{ local_non_root_user_ssh_private_key_file_path }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: yes
    ansible_become_method: sudo
    transfer_method: scp  
  
  roles:
    - role: lxd-initialise-host


