---
- name: Add project host as LXD remote on local control node
  hosts: local
  
  vars_files:
    - "{{ playbook_dir }}/../../../../ryo-control-node/configuration/configuration.yml"
    - "{{ playbook_dir }}/../../../configuration/configuration.yml"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"
  
  roles:
    - role: lxd-create-remotes-certs
    - role: lxd-set-up-control-node-remote


- name: Add local control node as LXD remote on host
  hosts: host_wireguard_ip
  
  vars_files:
    - "{{ playbook_dir }}/../../../../ryo-control-node/configuration/configuration.yml"
    - "{{ playbook_dir }}/../../../configuration/configuration.yml"
  
  vars:
    ansible_port: "{{ host_new_ssh_port }}"
    ansible_user: "{{ host_non_root_user }}"
    ansible_ssh_pass: "{{ host_non_root_user_password }}"
    ansible_ssh_private_key_file: "{{ local_non_root_user_ssh_private_key_file_path }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: yes
    ansible_become_method: sudo
    transfer_method: scp  
  
  roles:
    - role: lxd-set-up-project-host-remote
    - role: reboot-host
