---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Set up non root user
  hosts: host_control_ip
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../configuration/configuration_{{ host_id }}.yml"
  
  vars:
    ansible_port: "{{ host_initial_ssh_port }}"
    ansible_user: "{{ host_root_user }}"
    ansible_ssh_pass: "{{ host_root_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: no
    transfer_method: scp
  
  roles:
    - role: add-non-root-sudo-user


- name: Initial host setup
  hosts: host_control_ip
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../configuration/configuration_{{ host_id }}.yml"
  
  vars:
    ansible_port: "{{ host_initial_ssh_port }}"
    ansible_user: "{{ host_non_root_user }}"
    ansible_ssh_pass: "{{ host_non_root_user_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: yes
    ansible_become_method: sudo
    transfer_method: scp  
  
  roles:
    - role: system-upgrade
    - role: install-wireguard
    - role: set-up-wireguard-host
