---
- name: Add host consul as remote WAN server on control node
  hosts: local
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../configuration/configuration_{{ host_id }}.yml"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"
  
  roles:
    - role: set-up-consul-control-node
