---

## Add the control node CA cert as trusted

- name: Ensure certs directory exists
  file:
    path: /usr/local/share/ca-certificates
    state: directory

- name: Install CA certificate to certs directory
  copy:
    mode: 0664
    owner: root
    group: root
    dest: "/usr/local/share/ca-certificates/control-node-ca.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"

- name: Update certificate index
  shell:
    cmd: /usr/sbin/update-ca-certificates


## Add remotes configuration file on project host

## Ensure the host non-root user lxd configuration directory is present

# - name: Ensure the host non-root user lxd configuration directory is present
#   file:
#     owner: "{{ host_non_root_user }}"
#     group: "{{ host_non_root_user }}"
#     path: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/"
#     state: directory

# - name: Copy remotes configuration on project host
#   template:
#     mode: 0664
#     owner: "{{ host_non_root_user }}"
#     group: "{{ host_non_root_user }}"
#     dest: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/config.yml"
#     src: config.yml.j2


## Add project host client certificate and key

- name: Copy project host client certificate
  copy:
    mode: 0664
    owner: "{{ host_non_root_user }}"
    group: "{{ host_non_root_user }}"
    dest: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/client.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.crt"

- name: Copy project host client private key
  copy:
    mode: 0600
    owner: "{{ host_non_root_user }}"
    group: "{{ host_non_root_user }}"
    dest: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/client.key"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.key"


## Add control node server certificate

# - name: Ensure servercerts directory exists
#   file:
#     owner: "{{ host_non_root_user }}"
#     group: "{{ host_non_root_user }}"
#     path: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/servercerts"
#     state: directory

# - name: Copy control node server certificate
#   copy:
#     mode: 0664
#     owner: "{{ host_non_root_user }}"
#     group: "{{ host_non_root_user }}"
#     dest: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/servercerts/control-node-server.crt"
#     src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.crt"


## Add project host server certificate and key

- name: Copy project host server certificate
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.crt"

- name: Copy project host server private key
  copy:
    mode: 0600
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.key"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.key"


## Enable PKI mode: copy CA certificate to client and server configuration

- name: Copy CA certificate to control node server configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/var/snap/lxd/common/lxd/server.ca"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"

- name: Copy CA certificate to control node client configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: "/home/{{ host_non_root_user }}/snap/lxd/current/.config/lxc/client.ca"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"


## Add the control node as LXD trusted TLS client for the project host

- name: Copy control node client certificate to the project host
  copy:
    mode: 0644
    owner: "{{ host_non_root_user }}"
    group: "{{ host_non_root_user }}"
    dest: "/home/{{ host_non_root_user }}/control-node-client.crt"
    src: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.crt"

- name: Add the control node as LXD trusted TLS client for the project host
  shell:
    cmd: 'lxc config trust add /home/{{ host_non_root_user }}/control-node-client.crt'
  become: yes
  become_user: "{{ host_non_root_user }}"
