---

## Generate LXD server and client certs for the {{host_id}} host server

# Generate a {{host_id}} LXD server private key
- name: Generate a {{host_id}} LXD server private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-server.key"
    state: present
  register: ph_server_privatekey

# Generate a CSR for the {{host_id}} LXD server
- name: Generate a CSR for the {{host_id}} LXD server
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-server.csr"
    privatekey_path: "{{ ph_server_privatekey.filename }}"
    common_name: "{{host_id}}.ryo-project"
    subject_alt_name: "IP:{{ wireguard_address_network_part }}.2"
    organization_name: "rollyourown.xyz {{host_id}} Host"
    organizational_unit_name: "{{host_id}} Host"
    state: present
  register: ph_server_csr

# Sign the {{host_id}} LXD server CSR with the CA certificate and key
- name: Sign the {{host_id}} LXD server CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-server.crt"
    csr_path: "{{ ph_server_csr.filename }}"
    provider: ownca
    ownca_create_subject_key_identifier: always_create
    ownca_path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/ca.key"
    state: present

# Generate a {{host_id}} LXD client private key
- name: Generate a {{host_id}} LXD client private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-client.key"
    state: present
  register: ph_client_privatekey

# Generate a CSR for the {{host_id}} LXD client
- name: Generate a CSR for the {{host_id}} LXD client
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-client.csr"
    privatekey_path: "{{ ph_client_privatekey.filename }}"
    common_name: "{{host_id}}.ryo-project"
    organization_name: "rollyourown.xyz {{host_id}} Host"
    organizational_unit_name: "{{host_id}} Host"
    state: present
  register: ph_client_csr

# Sign the {{host_id}} LXD client CSR with the CA certificate and key
- name: Sign the {{host_id}} LXD client CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/{{host_id}}-client.crt"
    csr_path: "{{ ph_client_csr.filename }}"
    provider: ownca
    ownca_create_subject_key_identifier: always_create
    ownca_path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../ryo-control-node/configuration/ca/ca.key"
    state: present
