---

## Generate LXD server and client certs for the control node
  
# Generate a control node LXD server private key
- name: Generate a control node LXD server private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.key"
    state: present
  register: cn_server_privatekey

# Generate a CSR for the control node LXD server
- name: Generate a CSR for the control node LXD server
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.csr"
    privatekey_path: "{{ cn_server_privatekey.filename }}"
    common_name: "control.ryo-project"
    subject_alt_name: "IP:{{ wireguard_address_network_part }}.1"
    organization_name: "rollyourown.xyz Control Node"
    organizational_unit_name: "Control Node"
    state: present
  register: cn_server_csr

# Sign the control node LXD server CSR with the CA certificate and key
- name: Sign the control node LXD server CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-server.crt"
    csr_path: "{{ cn_server_csr.filename }}"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.key"
    state: present

# Generate a control node LXD client private key
- name: Generate a control node LXD client private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.key"
    state: present
  register: cn_client_privatekey

# Generate a CSR for the control node LXD client
- name: Generate a CSR for the control node LXD client
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.csr"
    privatekey_path: "{{ cn_client_privatekey.filename }}"
    common_name: "control.ryo-project"
    organization_name: "rollyourown.xyz Control Node"
    organizational_unit_name: "Control Node"
    state: present
  register: cn_client_csr

# Sign the control node LXD client CSR with the CA certificate and key
- name: Sign the control node LXD client CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/control-node-client.crt"
    csr_path: "{{ cn_client_csr.filename }}"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.key"
    state: present


## Generate LXD server and client certs for the {{project_id}} host server

# Generate a {{project_id}} LXD server private key
- name: Generate a {{project_id}} LXD server private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.key"
    state: present
  register: ph_server_privatekey

# Generate a CSR for the {{project_id}} LXD server
- name: Generate a CSR for the {{project_id}} LXD server
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.csr"
    privatekey_path: "{{ ph_server_privatekey.filename }}"
    common_name: "{{project_id}}.ryo-project"
    subject_alt_name: "IP:{{ wireguard_address_network_part }}.2"
    organization_name: "rollyourown.xyz {{project_id}} Host"
    organizational_unit_name: "{{project_id}} Host"
    state: present
  register: ph_server_csr

# Sign the {{project_id}} LXD server CSR with the CA certificate and key
- name: Sign the {{project_id}} LXD server CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-server.crt"
    csr_path: "{{ ph_server_csr.filename }}"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.key"
    state: present

# Generate a {{project_id}} LXD client private key
- name: Generate a {{project_id}} LXD client private key
  openssl_privatekey:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.key"
    state: present
  register: ph_client_privatekey

# Generate a CSR for the {{project_id}} LXD client
- name: Generate a CSR for the {{project_id}} LXD client
  openssl_csr:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.csr"
    privatekey_path: "{{ ph_client_privatekey.filename }}"
    common_name: "{{project_id}}.ryo-project"
    organization_name: "rollyourown.xyz {{project_id}} Host"
    organizational_unit_name: "{{project_id}} Host"
    state: present
  register: ph_client_csr

# Sign the {{project_id}} LXD client CSR with the CA certificate and key
- name: Sign the {{project_id}} LXD client CSR with the CA certificate and key
  openssl_certificate:
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/{{project_id}}-client.crt"
    csr_path: "{{ ph_client_csr.filename }}"
    provider: ownca
    ownca_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.crt"
    ownca_privatekey_path: "{{ playbook_dir }}/../../../../ryo-control-node/configuration/ca/ca.key"
    state: present
