---

## Generate LXD server and client certs for the control node
  
# Generate a control node LXD server private key
- name: Generate a control node LXD server private key
  openssl_privatekey:
    owner: root
    group: root
    path: /root/ca/control-node-server.pem
    state: present
  register: cn_server_privatekey

# Generate a CSR for the control node LXD server
- name: Generate a CSR for the control node LXD server
  openssl_csr:
    owner: root
    group: root
    path: /root/ca/control-node-server.csr
    privatekey_path: "{{ cn_server_privatekey.filename }}"
    common_name: "rollyourown.xyz Control Node"
    organization_name: "rollyourown.xyz Control Node"
    organizational_unit_name: "Control Node"
    state: present
  register: cn_server_csr

# Sign the control node LXD server CSR with the CA certificate and key
- name: Sign the control node LXD server CSR with the CA certificate and key
  openssl_certificate:
    owner: root
    group: root
    path: /root/ca/control-node-server.crt
    csr_path: "{{ cn_server_csr.filename }}"
    provider: ownca
    ownca_path: /root/ca/ca.crt
    ownca_privatekey_path: /root/ca/ca.pem
    state: present

# Generate a control node LXD client private key
- name: Generate a control node LXD client private key
  openssl_privatekey:
    owner: root
    group: root
    path: /root/ca/control-node-client.pem
    state: present
  register: cn_client_privatekey

# Generate a CSR for the control node LXD client
- name: Generate a CSR for the control node LXD client
  openssl_csr:
    owner: root
    group: root
    path: /root/ca/control-node-client.csr
    privatekey_path: "{{ cn_client_privatekey.filename }}"
    common_name: "rollyourown.xyz Control Node"
    organization_name: "rollyourown.xyz Control Node"
    organizational_unit_name: "Control Node"
    state: present
  register: cn_client_csr

# Sign the control node LXD client CSR with the CA certificate and key
- name: Sign the control node LXD client CSR with the CA certificate and key
  openssl_certificate:
    owner: root
    group: root
    path: /root/ca/control-node-client.crt
    csr_path: "{{ cn_client_csr.filename }}"
    provider: ownca
    ownca_path: /root/ca/ca.crt
    ownca_privatekey_path: /root/ca/ca.pem
    state: present


## Generate LXD server and client certs for the {{project_id}} host server

# Generate a {{project_id}} LXD server private key
- name: Generate a {{project_id}} LXD server private key
  openssl_privatekey:
    owner: root
    group: root
    path: "/root/ca/{{project_id}}-server.pem"
    state: present
  register: ph_server_privatekey

# Generate a CSR for the {{project_id}} LXD server
- name: Generate a CSR for the {{project_id}} LXD server
  openssl_csr:
    owner: root
    group: root
    path: /root/ca/{{project_id}}-server.csr
    privatekey_path: "{{ ph_server_privatekey.filename }}"
    common_name: "rollyourown.xyz {{project_id}} Host"
    organization_name: "rollyourown.xyz {{project_id}} Host"
    organizational_unit_name: "{{project_id}} Host"
    state: present
  register: ph_server_csr

# Sign the {{project_id}} LXD server CSR with the CA certificate and key
- name: Sign the {{project_id}} LXD server CSR with the CA certificate and key
  openssl_certificate:
    owner: root
    group: root
    path: "/root/ca/{{project_id}}-server.crt"
    csr_path: "{{ ph_server_csr.filename }}"
    provider: ownca
    ownca_path: /root/ca/ca.crt
    ownca_privatekey_path: /root/ca/ca.pem
    state: present

# Generate a {{project_id}} LXD client private key
- name: Generate a {{project_id}} LXD client private key
  openssl_privatekey:
    owner: root
    group: root
    path: "/root/ca/{{project_id}}-client.pem"
    state: present
  register: ph_client_privatekey

# Generate a CSR for the {{project_id}} LXD client
- name: Generate a CSR for the {{project_id}} LXD client
  openssl_csr:
    owner: root
    group: root
    path: "/root/ca/{{project_id}}-client.csr"
    privatekey_path: "{{ ph_client_privatekey.filename }}"
    common_name: "rollyourown.xyz {{project_id}} Host"
    organization_name: "rollyourown.xyz {{project_id}} Host"
    organizational_unit_name: "{{project_id}} Host"
    state: present
  register: ph_client_csr

# Sign the {{project_id}} LXD client CSR with the CA certificate and key
- name: Sign the {{project_id}} LXD client CSR with the CA certificate and key
  openssl_certificate:
    owner: root
    group: root
    path: "/root/ca/{{project_id}}-client.crt"
    csr_path: "{{ ph_client_csr.filename }}"
    provider: ownca
    ownca_path: /root/ca/ca.crt
    ownca_privatekey_path: /root/ca/ca.pem
    state: present
